import type { NextPage } from "next";
import Head from "next/head";
import CustomLink from "../components/CustomLink";
import { FaGithub } from "react-icons/fa";
import { motion } from "framer-motion";
import { useState } from "react";

const HomePage: NextPage = () => {
  const [isHovered, setHovered] = useState(false);

  return (
    <div>
      <Head>
        <title>Framer motion playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center h-screen tracking-widest">
        <h1
          className="p-4 text-2xl font-bold hover:text-orange-500 transition-all"
          onMouseEnter={() => setHovered(true)}
          onMouseLeave={() => setHovered(false)}
        >
          Let's build.{" "}
          <motion.div
            className="inline-block"
            animate={{
              scale: isHovered ? [1, 2] : 1,
              x: isHovered ? [0, 120] : 0,
              y: isHovered ? [0, -120] : 0,
            }}
            transition={{
              duration: 0.5,
              ease: "easeIn",
            }}
          >
            🚀
          </motion.div>{" "}
        </h1>
        <CustomLink
          href="https://github.com/terrytjw/t2-template"
          className="flex gap-4 p-4"
        >
          <FaGithub />
          Github repo
        </CustomLink>
      </main>
    </div>
  );
};

export default HomePage;
